"use client";

import styles from "./page.module.css";
import Link from "next/link";
import { useState, useEffect } from "react";
import { socket } from "../lib/socket";

interface Incident {
  id: number;
  type: string;
  location: string;
  time: string;
  severity: "critical" | "warning" | "info";
  desc?: string;
  aiData?: {
    translation?: string;
    severity?: string;
    room?: string;
    threatType?: string;
    summary?: string;
    protocol?: string[];
    instructions?: string;
  };
}

export default function ReportPage() {
  const [incidents, setIncidents] = useState<Incident[]>([]);

  useEffect(() => {
    socket.connect();

    socket.on("incident_history", (history: Incident[]) => {
      setIncidents(history.reverse());
    });

    socket.on("new_incident", (data: Incident) => {
      setIncidents(prev => [data, ...prev]);
    });

    return () => {
      socket.off("incident_history");
      socket.off("new_incident");
      socket.disconnect();
    };
  }, []);

  const severityIcon = (s: string) => s === "critical" ? "🚨" : s === "warning" ? "⚠️" : "ℹ️";

  return (
    <div className={styles.reportPage}>
      <div className={styles.header}>
        <div className={styles.headerLeft}>
          <div className={styles.headerIcon}>📋</div>
          <div>
            <div className={styles.headerTitle}>AI Incident Reports</div>
            <div className={styles.headerSub}>Auto-generated by Gemini 2.5 Flash</div>
          </div>
        </div>
        <div className={styles.headerRight}>
          <span className={styles.liveCount}>{incidents.length} reports</span>
          <Link href="/" className={styles.backLink}>← Home</Link>
        </div>
      </div>

      {incidents.length === 0 ? (
        <div className={styles.emptyState}>
          <div className={styles.emptyIcon}>📋</div>
          <div className={styles.emptyTitle}>No Incidents Yet</div>
          <div className={styles.emptyDesc}>
            When a guest sends an SOS message, Gemini will analyze it and generate a structured incident report here in real-time.
          </div>
        </div>
      ) : (
        <div className={styles.reportList}>
          {incidents.map((incident) => (
            <div
              key={incident.id}
              className={`${styles.reportCard} ${
                incident.severity === "critical" ? styles.reportCardCritical :
                incident.severity === "warning" ? styles.reportCardWarning : styles.reportCardInfo
              }`}
            >
              {/* Card Header */}
              <div className={styles.cardTop}>
                <div className={styles.cardTopLeft}>
                  <div className={`${styles.severityBadge} ${
                    incident.severity === "critical" ? styles.severityCritical :
                    incident.severity === "warning" ? styles.severityWarning : styles.severityInfo
                  }`}>
                    {severityIcon(incident.severity)}
                  </div>
                  <div>
                    <div className={styles.cardTitle}>{incident.type}</div>
                    <div className={styles.cardMeta}>
                      <span>📍 {incident.location}</span>
                      <span>🕐 {incident.time}</span>
                    </div>
                  </div>
                </div>
                <div className={styles.cardTopRight}>
                  <span className={`${styles.severityTag} ${
                    incident.severity === "critical" ? styles.tagCritical :
                    incident.severity === "warning" ? styles.tagWarning : styles.tagInfo
                  }`}>
                    {incident.severity}
                  </span>
                  <span className={styles.cardId}>ID: {incident.id}</span>
                </div>
              </div>

              {/* Card Body */}
              <div className={styles.cardBody}>
                {/* AI Summary */}
                {incident.aiData?.summary && (
                  <div className={styles.section}>
                    <div className={styles.sectionLabel}>🤖 AI Summary</div>
                    <div className={styles.sectionValue}>{incident.aiData.summary}</div>
                  </div>
                )}

                {/* Translation */}
                {incident.aiData?.translation && (
                  <div className={styles.section}>
                    <div className={styles.sectionLabel}>🌐 Translation / Source</div>
                    <div className={styles.translationBox}>{incident.aiData.translation}</div>
                  </div>
                )}

                {/* Two column: Threat Type + Room */}
                <div className={styles.twoCol}>
                  <div className={styles.section}>
                    <div className={styles.sectionLabel}>Threat Type</div>
                    <div className={styles.sectionValue}>{incident.aiData?.threatType || incident.type}</div>
                  </div>
                  <div className={styles.section}>
                    <div className={styles.sectionLabel}>Extracted Location</div>
                    <div className={styles.sectionValue}>{incident.aiData?.room || incident.location}</div>
                  </div>
                </div>

                {/* Protocol */}
                {incident.aiData?.protocol && incident.aiData.protocol.length > 0 && (
                  <div className={styles.section}>
                    <div className={styles.sectionLabel}>🎯 Recommended Protocol</div>
                    <ol className={styles.protocolSteps}>
                      {incident.aiData.protocol.map((step, idx) => (
                        <li key={idx}>{step}</li>
                      ))}
                    </ol>
                  </div>
                )}

                {/* Guest instructions */}
                {incident.aiData?.instructions && (
                  <div className={styles.section}>
                    <div className={styles.sectionLabel}>📱 Instructions Sent to Guest</div>
                    <div className={styles.sectionValue}>{incident.aiData.instructions}</div>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
